### ISSUE TITLE
event page and signup buttons don't update properly

### ISSUE THREAD

**Issue by Ciuffi** [nwplus/LHD2020#51]
In the events section, the buttons for the event page and the signup form are greyed out at all times. We need to be able to change these depending on firebase variables. (aka, enable/disable them through the cms)

eg: 
<img width="539" alt="image" src="https://user-images.githubusercontent.com/26512016/69096158-bcb1b380-0a08-11ea-8242-a46187dccb8e.png">

**Comment by luceliu** [comment]
@Ciuffi I'm confused, it seems on `dev` branch that this is already implemented? In Button.vue: 
```
<p :class="`but-text ${disabled ? 'disabled' : ''}`">{{ title }}</p>
```

and Events.vue
```
<Button :disabled="!item.signupEnabled" title="Sign up" :url="item.signupLink || '#'" class="buttonLabel" />
<Button :disabled="!item.signupEnabled" title="Event page" :url="item.eventLink || '#'" class="buttonLabel" />
```
Lemme know if i'm misinterpreting the issue

**Comment by Ciuffi** [comment]
@luceliu  its implemented in LHD but not in the CMS. I implemented it when I did that part in LHD, not sure who did the CMS part but I think they misunderstood what those variables were supposed to do.

**Comment by Ciuffi** [comment]
@luceliu I guess just do the cms part

**Comment by Ciuffi** [comment]
@luceliu Actually better idea, Why don't you make it so the buttons are disabled if the link is a blank string? That way we can just remove the link on the cms and it'll automatically disable the button, and we don't have to make any changes to the CMS.

eg:
instead of:
```vue
<Button :disabled="!item.signupEnabled" title="Sign up" :url="item.signupLink || '#'" class="buttonLabel" />
<Button :disabled="!item.signupEnabled" title="Event page" :url="item.eventLink || '#'" class="buttonLabel" />
```
we do
```vue
<Button :disabled="item.signupLink && item.signupLink === ''" title="Sign up" :url="item.signupLink || '#'" class="buttonLabel" />
<Button :disabled="item.eventLink && item.eventLink === ''" title="Event page" :url="item.eventLink || '#'" class="buttonLabel" />
```

Let me know what you think.

**Comment by luceliu** [comment]
makes sense to me!

**Comment by luceliu** [comment]
wait i thought there was more work but i think that's literally all that needs to be done other than adding blank signupLinks to the cms

**Comment by Ciuffi** [comment]
Pretty much LOL do you wanna do it or should I?

**Comment by Ciuffi** [comment]
They don’t even need to be blank, if it doesn’t exist then it’ll count as disabled tok (in my example) 

So I don’t even think we have to update the cms (unless we have to remove old links)

**Comment by luceliu** [comment]
i already did it lol i'll do PR
